name: 'Readable: Semantic Line Breaks'
description: 'Opinionated Markdown formatter, featuring semantic line breaks'
branding:
  icon: 'align-left'
  color: 'orange'
inputs:
  glob:
    description: 'target files glob pattern'
    required: true
    default: '**.md'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - check
    - ${{ inputs.glob }}
