name: Publish (release)

on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.33.4
    - run: ./dev env
    - run: ./dev build docker
    - name: Publish to GitHub Container Registry
      run: |
        echo ${{ secrets.GH_PACKAGES_TOKEN }} | docker login ghcr.io --username $GITHUB_ACTOR --password-stdin
        docker tag bobheadxi/readable:$(./dev env revision) ghcr.io/bobheadxi/readable:$(git describe --tags)
        docker push ghcr.io/bobheadxi/readable:$(git describe --tags)
